(function(){
  // Enhancements: manager, local storage, custom sequence editor and timer controller
  const LS_EX = 'wt_exercises_v1';
  const LS_GOLPES = 'wt_golpes_v1';
  const LS_ASSIGN = 'wt_assign_v1';
  const LS_ROUND_DUR = 'wt_round_dur_v1';

  function loadJSON(k, f){ try { return JSON.parse(localStorage.getItem(k) || 'null') || f; } catch(e){ return f; } }
  function saveJSON(k, v){ localStorage.setItem(k, JSON.stringify(v)); }

  if (!loadJSON(LS_GOLPES, null)) saveJSON(LS_GOLPES, [{id:'g1',name:'Jab'},{id:'g2',name:'Direto'},{id:'g3',name:'Gancho'}]);
  if (!loadJSON(LS_EX, null)) saveJSON(LS_EX, [{id:'e1',name:'Combinação 1',golpes:['g1','g2']},{id:'e2',name:'Padrão 2',golpes:['g3']}]);

  // DOM refs
  const configView = document.getElementById('configView');
  const timerView = document.getElementById('timerView');
  const seqTrackEl = document.getElementById('seqTrack');
  const phaseLabelEl = document.getElementById('phaseLabel');
  const roundCountEl = document.getElementById('roundCount');
  const timeTextEl = document.getElementById('timeText');
  const nextPhaseEl = document.getElementById('nextPhase');
  const ringEl = document.getElementById('ringProgress');

  // Inject left panel with golpes and manager button
  const golpesPanel = document.createElement('div'); golpesPanel.id='golpesPanel';
  golpesPanel.style.cssText = 'position:fixed;left:12px;top:100px;width:150px;max-height:70vh;overflow:auto;background:linear-gradient(180deg, rgba(19,16,25,0.9), rgba(28,23,38,0.9));border:1px solid rgba(192,132,252,0.12);padding:10px;border-radius:12px;font-size:13px;z-index:1200;color:var(--text);';
  golpesPanel.innerHTML = '<div style="font-weight:800;color:var(--purple-bright);margin-bottom:8px;">Golpes</div><div id="golpesList"></div><div style="margin-top:8px;"><button id="openManagerBtn" style="width:100%;">Gerenciar exercícios</button></div>';
  document.body.appendChild(golpesPanel);
  document.getElementById('openManagerBtn').addEventListener('click', openManager);

  function renderGolpesPanel(exId){ const golpes = loadJSON(LS_GOLPES,[]); const exList = loadJSON(LS_EX,[]); const list=document.getElementById('golpesList'); list.innerHTML=''; golpes.forEach(g=>{ const d=document.createElement('div'); d.textContent=g.name; d.style.marginBottom='6px'; list.appendChild(d); }); if(exId){ const ex = exList.find(x=>x.id===exId); if(ex){ const h=document.createElement('div'); h.style.marginTop='8px'; h.style.fontWeight='700'; h.textContent='Ex: '+ex.name; list.appendChild(h); (ex.golpes||[]).forEach(gid=>{ const g = golpes.find(x=>x.id===gid); if(g){ const d=document.createElement('div'); d.textContent='• '+g.name; d.style.marginLeft='6px'; list.appendChild(d); } }); } } }

  // Manager modal
  let managerModal=null;
  function openManager(){ if(managerModal){ managerModal.style.display='block'; return; } managerModal=document.createElement('div'); managerModal.style.cssText='position:fixed;left:50%;top:50%;transform:translate(-50%,-50%);z-index:2000;width:760px;max-width:96%;max-height:80vh;overflow:auto;background:var(--surface);border:1px solid rgba(192,132,252,0.12);border-radius:12px;padding:14px;color:var(--text);'; managerModal.innerHTML=`<div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:8px;"><h3 style="margin:0">Gerenciar exercícios e golpes</h3><button id="closeMgr">Fechar</button></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:12px;"><div><h4>Golpes</h4><div id="mgrGolpes"></div><div style="margin-top:8px;display:flex;gap:8px;"><input id="newGolpe" placeholder="Nome do golpe" style="flex:1;"><button id="addGolpe">Adicionar</button></div></div><div><h4>Exercícios</h4><div id="mgrEx"></div><div style="margin-top:8px;display:flex;gap:8px;"><input id="newEx" placeholder="Nome do exercício" style="flex:1;"><button id="addEx">Adicionar</button></div></div></div><hr><div><h4>Atribuir exercício a rounds</h4><div id="mgrAssign"></div></div>`; document.body.appendChild(managerModal); document.getElementById('closeMgr').addEventListener('click', ()=>managerModal.style.display='none'); document.getElementById('addGolpe').addEventListener('click', ()=>{ const name=document.getElementById('newGolpe').value.trim(); if(!name) return alert('Digite nome'); const g=loadJSON(LS_GOLPES,[]); const id='g'+Date.now(); g.push({id,name}); saveJSON(LS_GOLPES,g); document.getElementById('newGolpe').value=''; renderManager(); renderGolpesPanel(null); }); document.getElementById('addEx').addEventListener('click', ()=>{ const name=document.getElementById('newEx').value.trim(); if(!name) return alert('Digite nome'); const ex=loadJSON(LS_EX,[]); const id='e'+Date.now(); ex.push({id,name,golpes:[]}); saveJSON(LS_EX,ex); document.getElementById('newEx').value=''; renderManager(); renderGolpesPanel(null); }); renderManager(); }

  function renderManager(){ const golpes = loadJSON(LS_GOLPES,[]); const exs = loadJSON(LS_EX,[]); const mg=document.getElementById('mgrGolpes'); mg.innerHTML=''; golpes.forEach(g=>{ const d=document.createElement('div'); d.style.display='flex'; d.style.justifyContent='space-between'; d.style.marginBottom='6px'; d.innerHTML=`<span>${g.name}</span><button data-id="${g.id}" class="delG">Excluir</button>`; mg.appendChild(d); }); const me=document.getElementById('mgrEx'); me.innerHTML=''; exs.forEach(e=>{ const d=document.createElement('div'); d.style.marginBottom='8px'; d.innerHTML=`<div style="display:flex;justify-content:space-between;align-items:center;"><strong>${e.name}</strong><button data-id="${e.id}" class="delE">Excluir</button></div><div id="exg_${e.id}" style="margin-top:6px"></div>`; me.appendChild(d); const box=document.getElementById('exg_'+e.id); golpes.forEach(g=>{ const lbl=document.createElement('label'); lbl.style.marginRight='8px'; const inp=document.createElement('input'); inp.type='checkbox'; inp.checked = (e.golpes||[]).indexOf(g.id)!==-1; inp.addEventListener('change', ()=>{ const all=loadJSON(LS_EX,[]); const tar = all.find(x=>x.id===e.id); if(!tar.golpes) tar.golpes=[]; if(inp.checked) tar.golpes.push(g.id); else tar.golpes = tar.golpes.filter(id=>id!==g.id); saveJSON(LS_EX, all); renderGolpesPanel(null); }); lbl.appendChild(inp); lbl.appendChild(document.createTextNode(' '+g.name)); box.appendChild(lbl); }); }); mg.querySelectorAll('.delG').forEach(b=> b.addEventListener('click', ()=>{ const id=b.dataset.id; let g=loadJSON(LS_GOLPES,[]); g=g.filter(x=>x.id!==id); saveJSON(LS_GOLPES,g); let ex=loadJSON(LS_EX,[]); ex.forEach(e=> e.golpes = (e.golpes||[]).filter(x=>x!==id)); saveJSON(LS_EX,ex); renderManager(); renderGolpesPanel(null); })); me.querySelectorAll('.delE').forEach(b=> b.addEventListener('click', ()=>{ const id=b.dataset.id; let ex=loadJSON(LS_EX,[]); ex=ex.filter(x=>x.id!==id); saveJSON(LS_EX,ex); const assigns = loadJSON(LS_ASSIGN,{}); Object.keys(assigns).forEach(k=>{ if(assigns[k]===id) delete assigns[k]; }); saveJSON(LS_ASSIGN,assigns); renderManager(); })); renderAssigns(); }

  function renderAssigns(){ const assigns = loadJSON(LS_ASSIGN,{}); const roundDurs = loadJSON(LS_ROUND_DUR,{}); const ex = loadJSON(LS_EX,[]); const rounds = parseInt(document.getElementById('cfgRounds').value,10) || 1; const cont=document.getElementById('mgrAssign'); cont.innerHTML=''; for(let r=1;r<=rounds;r++){ const row=document.createElement('div'); row.style.display='flex'; row.style.gap='8px'; row.style.alignItems='center'; row.style.marginBottom='6px'; const lbl=document.createElement('div'); lbl.textContent='Round '+r; lbl.style.width='70px'; const sel=document.createElement('select'); sel.style.flex='1'; const opt=document.createElement('option'); opt.value=''; opt.textContent='— (Nenhum)'; sel.appendChild(opt); ex.forEach(e=>{ const o=document.createElement('option'); o.value=e.id; o.textContent=e.name; if(assigns['r'+r]===e.id) o.selected=true; sel.appendChild(o); }); sel.addEventListener('change', ()=>{ assigns['r'+r] = sel.value || null; saveJSON(LS_ASSIGN, assigns); }); const minInput = document.createElement('input'); minInput.type='number'; minInput.style.width='60px'; minInput.min=0; minInput.placeholder='min'; const secInput = document.createElement('input'); secInput.type='number'; secInput.style.width='60px'; secInput.min=0; secInput.max=59; secInput.placeholder='seg'; const saved = roundDurs['r'+r]; if(typeof saved === 'number'){ minInput.value = Math.floor(saved/60); secInput.value = saved%60; } else { minInput.value=''; secInput.value=''; } minInput.addEventListener('change', ()=>{ const m = parseInt(minInput.value,10)||0; const s = parseInt(secInput.value,10)||0; roundDurs['r'+r] = m*60 + s; saveJSON(LS_ROUND_DUR, roundDurs); }); secInput.addEventListener('change', ()=>{ const m = parseInt(minInput.value,10)||0; const s = parseInt(secInput.value,10)||0; roundDurs['r'+r] = m*60 + s; saveJSON(LS_ROUND_DUR, roundDurs); }); const durWrap = document.createElement('div'); durWrap.style.display='flex'; durWrap.style.gap='4px'; durWrap.appendChild(minInput); durWrap.appendChild(secInput); row.appendChild(lbl); row.appendChild(sel); row.appendChild(durWrap); cont.appendChild(row); } }

  // Local timer (independent) to avoid interfering with original script
  let SEQ = [], idx=0, remaining=0, running=false, timerHandle=null;
  function buildSequenceFromConfig(){ const toSec=(minEl,secEl)=>{const m=Math.max(0,parseInt(minEl.value,10)||0);const s=Math.max(0,Math.min(59,parseInt(secEl.value,10)||0));return m*60+s;}; const warmup=toSec(document.getElementById('cfgWarmupMin'),document.getElementById('cfgWarmupSec')); const rounds=Math.max(1,parseInt(document.getElementById('cfgRounds').value,10)||1); const trocaEvery=Math.max(0,parseInt(document.getElementById('cfgTrocaEvery').value,10)||0); const defaultRoundDur=toSec(document.getElementById('cfgRoundMin'),document.getElementById('cfgRoundSec')); const restDur=toSec(document.getElementById('cfgRestMin'),document.getElementById('cfgRestSec')); const trocaDur=toSec(document.getElementById('cfgTrocaMin'),document.getElementById('cfgTrocaSec')); const endDur=toSec(document.getElementById('cfgEndMin'),document.getElementById('cfgEndSec'));
    const roundDurs = loadJSON(LS_ROUND_DUR,{});
    const seq=[]; if(warmup>0) seq.push({type:'warmup',label:'Aquecimento',duration:warmup,round:null}); for(let r=1;r<=rounds;r++){ const rdKey = 'r'+r; const rd = (typeof roundDurs[rdKey] === 'number' && roundDurs[rdKey] > 0) ? roundDurs[rdKey] : defaultRoundDur; seq.push({type:'round',label:'Round '+r,duration:rd,round:r}); if(r===rounds) continue; const isTroca = trocaEvery>0 && (r%trocaEvery===0); if(isTroca){ if(trocaDur>0) seq.push({type:'troca',label:'Troca',duration:trocaDur,round:r}); } else { if(restDur>0) seq.push({type:'rest',label:'Descanso',duration:restDur,round:r}); } } if(endDur>0) seq.push({type:'end',label:'Encerramento',duration:endDur,round:null}); const assigns = loadJSON(LS_ASSIGN,{}); seq.forEach(p=>{ if(p.type==='round') p.exerciseId = assigns['r'+p.round] || null; }); return seq; }

  function renderAll(){ if(!SEQ.length) return; const phase = SEQ[idx]; const cls = phase.type==='rest'?'rest':(phase.type==='troca'?'troca':(phase.type==='end'?'end':'')); phaseLabelEl.textContent = phase.label; phaseLabelEl.className = 'phase-label'+(cls? ' '+cls:''); const totalRounds = SEQ.filter(p=>p.type==='round').length; if(phase.round) roundCountEl.textContent = 'Round '+phase.round+' / '+totalRounds; else if(phase.type==='warmup') roundCountEl.textContent='Aquecimento'; else if(phase.type==='end') roundCountEl.textContent='Treino concluído'; else roundCountEl.textContent='— / '+totalRounds; timeTextEl.textContent = Math.floor(remaining/60)+':'+String(remaining%60).padStart(2,'0'); const next = SEQ[idx+1]; nextPhaseEl.textContent = next?('Próximo: '+next.label):'Fim do treino'; const CIRC = parseFloat(ringEl.getAttribute('stroke-dasharray')||650); const frac = phase.duration>0?(remaining/phase.duration):0; ringEl.style.strokeDashoffset = (CIRC*(1-frac)).toFixed(2); renderSeqTrack(); renderGolpesPanel(phase.exerciseId); }

  function renderSeqTrack(){ seqTrackEl.innerHTML=''; SEQ.forEach((p,i)=>{ const seg=document.createElement('div'); let label='·'; if(p.type==='warmup') label='AQ'; else if(p.type==='end') label='FIM'; else if(p.type==='round') label='R'+p.round; else if(p.type==='troca') label='TR'; seg.className='seg '+p.type; if(i<idx) seg.classList.add('done'); if(i===idx) seg.classList.add('current'); seg.textContent=label; seqTrackEl.appendChild(seg); }); const cur = seqTrackEl.querySelector('.current'); if(cur) cur.scrollIntoView({inline:'center',block:'nearest'}); }

  function startLocal(){ if(running || !SEQ.length) return; running=true; timerHandle = setInterval(()=>{ remaining -=1; if(remaining<=3 && remaining>0){ /* tick */ } if(remaining<0){ if(idx<SEQ.length-1){ idx++; remaining = SEQ[idx].duration; } else { running=false; clearInterval(timerHandle); } } renderAll(); }, 1000); }
  function pauseLocal(){ running=false; clearInterval(timerHandle); }
  function resetLocal(){ running=false; clearInterval(timerHandle); idx=0; remaining = SEQ.length?SEQ[0].duration:0; renderAll(); }

  // detach original handlers by replacing nodes and re-binding
  function replaceAndBind(id, handler){ const el=document.getElementById(id); if(!el) return null; const neo = el.cloneNode(true); el.parentNode.replaceChild(neo, el); neo.addEventListener('click', handler); return neo; }

  replaceAndBind('startClassBtn', ()=>{ SEQ = buildSequenceFromConfig(); idx=0; remaining = SEQ[0].duration; resetLocal(); renderAll(); configView.style.display='none'; timerView.style.display='block'; document.getElementById('seqTitleWrap').style.display='block'; document.getElementById('footerNote').style.display='block'; });
  replaceAndBind('startBtn', startLocal);
  replaceAndBind('pauseBtn', pauseLocal);
  replaceAndBind('resetBtn', resetLocal);
  replaceAndBind('forwardBtn', ()=>{ if(idx<SEQ.length-1){ idx++; remaining = SEQ[idx].duration; renderAll(); } });
  replaceAndBind('backBtn', ()=>{ if(idx>0){ idx--; remaining = SEQ[idx].duration; renderAll(); } });
  replaceAndBind('editConfigBtn', ()=>{ pauseLocal(); timerView.style.display='none'; configView.style.display='block'; document.getElementById('seqTitleWrap').style.display='none'; document.getElementById('footerNote').style.display='none'; });

  // initial render
  renderGolpesPanel(null);
  // re-render golpes when storage changes (simple interval)
  setInterval(()=>{ renderGolpesPanel(null); }, 3000);

})();